language: java
jdk:
  - oraclejdk8
dist: trusty
services:
  - xvfb
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
install:
  - ./gradlew --version
  - ./gradlew assemble --info
script:
  - xvfb-run --server-args="-screen 0 1024x768x24" ./gradlew test --tests tech.romashov.e2e.tests.AsClassicFestTest
  - xvfb-run --server-args="-screen 0 1024x768x24" ./gradlew test --tests tech.romashov.e2e.tests.AsProduction

notifications:
  email: false
