language: java
jdk:
  - oraclejdk9
dist: focal
services:
  - xvfb
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
install:
  - gradle --version
  - gradle assemble --info
script:
  - printenv

notifications:
  email: false
