/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tech.romashov;

import javax.swing.JFrame;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        JFrame.setDefaultLookAndFeelDecorated(true);
        new ContentPaneReplace();
    }
}
