# This is a basic workflow to help you get started with Actions

name: CI

on: 
  push:
  pull_request:
    types: [opened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt-hotspot'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1
      with:
        run: |
          ./gradlew test --tests tech.romashov.e2e.tests.AsClassicFestTest
          ./gradlew test --tests tech.romashov.e2e.tests.AsProduction
        working-directory: ./ #optional
        options: #optional
    - uses: actions/upload-artifact@v2
      with:
        name: videos
        path: ./video
    - uses: actions/upload-artifact@v2
      with:
        name: tests.log
        path: ./logs/tests.log

